# Generated by Django 3.1.2 on 2020-10-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField(default=0)),
                ('add', models.CharField(max_length=50)),
            ],
        ),
    ]
